Ignore ptr_arg clippy lint due to false positive
https://github.com/rust-lang/rust-clippy/issues/9218

    error: using a reference to `Cow` is not recommended
       --> src/libyaml/parser.rs:101:12
        |
    101 |     input: &Cow<'input, [u8]>,
        |            ^^^^^^^^^^^^^^^^^^ help: change this to: `&[u8]`
        |
        = note: `-D clippy::ptr-arg` implied by `-D clippy::all`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg