Add regression test for issue 327
Currently fails with:

    ---- test_python_safe_dump stdout ----
    thread 'test_python_safe_dump' panicked at 'called `Result::unwrap()` on an `Err` value:
    Error("foo: invalid type: integer `7200`, expected u32", line: 1, column: 8)', tests/test_de.rs:17:54