Raise required toolchain to rust 1.58
    error[E0277]: expected a `FnMut<(char,)>` closure, found `[char; 2]`
       --> src/de.rs:890:38
        |
    890 |     let scalar = scalar.strip_prefix(['-', '+']).unwrap_or(scalar);
        |                         ------------ ^^^^^^^^^^ expected an `FnMut<(char,)>` closure, found `[char; 2]`
        |                         |
        |                         required by a bound introduced by this call
        |
        = help: the trait `FnMut<(char,)>` is not implemented for `[char; 2]`
        = note: required because of the requirements on the impl of `Pattern<'_>` for `[char; 2]`