Fix unused import warnings in test under cfg miri
    error: unused imports: `SeqAccess`, `Visitor`
     --> tests/test_error.rs:4:30
      |
    4 | use serde::de::{Deserialize, SeqAccess, Visitor};
      |                              ^^^^^^^^^  ^^^^^^^
      |
      = note: `-D unused-imports` implied by `-D warnings`

    error: unused import: `std::collections::BTreeMap`
     --> tests/test_error.rs:8:5
      |
    8 | use std::collections::BTreeMap;
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: unused import: `self`
     --> tests/test_error.rs:9:16
      |
    9 | use std::fmt::{self, Debug};
      |                ^^^^

    error: miri cannot be run on programs that fail compilation