Raise minimum compiler to 1.38
Required by indexmap's dependency on hashbrown:

    error[E0658]: use of unstable library feature 'ptr_cast'
       --> hashbrown-0.11.2/src/raw/mod.rs:504:57
        |
    504 |         NonNull::new_unchecked(self.table.ctrl.as_ptr().cast())
        |                                                         ^^^^